spring.profiles.active=local
 
#AWSへのデプロイ準備作業で有効にする
#spring.profiles.active=aws
 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
 
spring.mail.username=sagarmatha603@gmail.com
spring.mail.password=ozbk yetf issn yxvr
 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 臨時追加：金城
# 1ファイルあたりの最大サイズ
spring.servlet.multipart.max-file-size=10MB
# リクエスト全体の最大サイズ
spring.servlet.multipart.max-request-size=10MB
# セッション切れ対策（開発中限定）
server.servlet.session.timeout=3600